### ISSUE TITLE
Incorrect lateness?

### ISSUE THREAD

**Issue by wohlbier** [LLNL/ravel#4]
I'm looking at some otf2 files in Ravel and trying to understand them. In the attached 2 figures Ravel shows lateness on rank 0, but I don't see how it's correct. From the physical timeline it looks like rank 0 is early, not late.

The code issues non-blocking recv's before blocking sends, if that matters.

![ravel - 2-traces otf2_002](https://cloud.githubusercontent.com/assets/8867238/18967315/aff6b1d2-8652-11e6-8668-75f1e41832e1.png)
![ravel - 2-traces otf2_003](https://cloud.githubusercontent.com/assets/8867238/18967322/b55da28e-8652-11e6-957e-1f7e85a12ee2.png)

**Comment by wohlbier** [comment]
Ok, I think I see why the non communication event is marked as late. It's the event exit time that comes later than all of it's peers. Is rank 0's lateness "back propagated" to the MPI_Send that's connected to it on rank 4? I.e., the MPI_Send was issued on rank 4 and since the non communication event on rank 0 was late the corresponding recv wasn't issued until later, and hence the already posted corresponding MPI_Send is part of a late Send/Recv pair?

Any other insights you have into my graphs are appreciated.

jgw

**Comment by kisaacs** [comment]
The first red MPI_Send at rank 4 is not being calculated at the same logical step as the first red MPI_Send at rank 0. They're only compared to events at their same logical step. Compared to all the sends in the column, the first red MPI_Send at rank 0 finished later. There is no back propagation. Does that help?

In the import options, do you have 'idealized order of sends and recvs" checked? This could affect what logical step both of those two function calls are placed at.

**Comment by wohlbier** [comment]
Hi Kate,
Thanks for the reply. I don't have that option.
![otf import options_001](https://cloud.githubusercontent.com/assets/8867238/18971327/aff6074a-8662-11e6-8350-82a935db9c5f.png)

**Comment by wohlbier** [comment]
MPI_Send events are being placed at the same logical time step even though they are occurring in separate exchanges, where I'm calling an exchange one of the two blobs in the physical view. So the reason the rank 4 MPI_Send is being called late even though it appears to enter the exchange first, it's b/c it's being compared to MPI_Sends in the previous exchange. That doesn't seem right, does it?

**Comment by kisaacs** [comment]
Thanks. Yes, there must be something confusing the algorithm's partitioning and thus causing that to happen. You can try it without "Advanced Stepping" or "Merge by Call Tree" and see if that helps (the Waitall Merge only operates on OTF, not OTF2). Also if the file is transferrable, I can take a look at it. I'm always looking to improve the algorithm.

**Comment by wohlbier** [comment]
Kate,
Without those options selected I get the following image. Doesn't look like there is much lateness. I'm not sure if that's good or bad ;)
![ravel - 2-traces otf2_001](https://cloud.githubusercontent.com/assets/8867238/18972200/38953370-8666-11e6-8e98-be43fef0d6ec.png)

Attached is the trace file. Thanks for looking!

jgw

[trace.zip](https://github.com/LLNL/ravel/files/501688/trace.zip)

**Comment by kisaacs** [comment]
Thanks! It looks like Ravel was being too aggressive with the call tree merge. I'll look into it. 

The lateness color bar is dominated by an early MPI_Gather (the tallest bar in the Overivew, ~0.4 seconds). It makes everything look blue in comparison. You can click on the color bar or the label to adjust -- the rest starts turning colors at maybe 0.1 or 0.2 seconds. I should add a duration metric like for Charm++ so you can compare the duration of things at the same logical step more easily.

**Comment by wohlbier** [comment]
Is there a way to save the OTF import settings?

**Comment by kisaacs** [comment]
There is -now- a way to save the OTF import settings. :) It should now read whatever there was when you closed the program.

I still need to look more closely, but my intuition on the difference in time is that with the 'merge Partitions by call tree', it gets to skip a bunch of logic and just assume everything called under a certain subtree is the same. With the option off, it has to do more work to figure out how to divide up communication phases.

For this trace I don't think the 'advanced stepping' is different than basic stepping once the phase detection is correct.

**Comment by wohlbier** [comment]
Thanks for the feature!

Any clues or recommendations about the windowing stuff? On my Linux VM the figures will only show up if I mouse over them, so I can't display logical/cluster/physical traces concurrently. I will try to nuke the entire Qt5 tree in spack and start over unless you have a better recommendation.

Thanks!
jgw

**Comment by kisaacs** [comment]
I don't know what might be causing the windowing problem. It's been a while since I tried the spack install, so I'll have to check if I get the same behavior.

**Comment by wohlbier** [comment]
Ok, thanks. I have a working installation with spack on REL6 (I think). The one that is wonky is on an Ubuntu VM on a mac. I think it's 14.04 but can't be sure until tonight.
