### ISSUE TITLE
QColor::setRgb: RGB parameters out of range

### ISSUE THREAD

**Issue by pramodk** [LLNL/ravel#6]
I am visualising sample otf2 trace and I see lots of messages: 
{code}
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
....
{code}

Is there any obvious reason for these warning messages? (see attached screenshot)

Also, is there any way to colorise the user functions? for example, in the attached screenshot, all user instrumented functions appears in black colour.

![ravel_otf2](https://cloud.githubusercontent.com/assets/666852/21079336/b9d79e84-bf8f-11e6-92cf-cf82883331f1.png)

**Comment by kisaacs** [comment]
Yes this looks like a bug in the color calculation. They should be in grayscale indicating their depth in the call hierarchy and I'm guessing the out of range turns everything to black. Do you have a small sample file where this happens?

There isn't currently a way to colorise the user functions other than the gray scale.

**Comment by pramodk** [comment]
>  Do you have a small sample file where this happens?

Sure! Could you try loading attached small trace file? [scorep_test.zip](https://github.com/LLNL/ravel/files/646813/scorep_test.zip)

**Comment by kisaacs** [comment]
Thanks! I've set a max value that should get rid of the RGB issues and maintain the gray scale, essentially clamping at a certain depth.

**Comment by pramodk** [comment]
Perfect! looks fine now!
