### ISSUE TITLE
segfault while opening otf trace

### ISSUE THREAD

**Issue by pramodk** [LLNL/ravel#7]
I am able to visualise *otf2* traces without any issues. 

I was also playing with *otf* traces provided on [vampir.eu website]:(https://www.vampir.eu/downloads/tracefiles)
```bash
small trace file => https://www.vampir.eu/public/files/tracefiles/Small.zip
```

When I try to open trace file, it segfault at below location:

```bash
Processing /Users/kumbhar/Downloads/Small/wrf.otf
Reading definitions
Reading events
Finish reading
0 unmatched sends and 0 unmatched recvs.
OTF Reading: 0.667056 seconds
Event/Message Matching: 0.935606 seconds
Merging for messages...
Partition Merge: 0.187787 seconds
Message Merge: 0.304303 seconds
Merging cycles...
Setting partition dag...
Tarjan...
Merging from the cycles...
Partition Merge: 0.150744 seconds
Cycle Merge: 0.224786 seconds
Setting DAG leaps...
Assigning local steps
Local Stepping: 0.032864 seconds
Setting global steps
Global Stepping: 0.0151446 seconds
Total Algorithm Time: 0.587945 seconds
Calculating step-wise metrics
Process 17290 stopped
* thread #16: tid = 0x285770c, 0x00000001000b52d0 Ravel`Metrics::setMetric(this=<unavailable>, name=<unavailable>, event_value=0, aggregate_value=0) + 64 at metrics.cpp:29, name = 'QThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001000b52d0 Ravel`Metrics::setMetric(this=<unavailable>, name=<unavailable>, event_value=0, aggregate_value=0) + 64 at metrics.cpp:29
   26  	                          double aggregate_value)
   27  	{
   28  	    MetricPair * mp = metrics->value(name);
-> 29  	    mp->event = event_value;
   30  	    mp->aggregate = aggregate_value;
   31  	}
   32
```

p.s. I am not using/generation *otf1* traces but thought I should just report the issue.

**Comment by pramodk** [comment]
thanks for quick fix! all looks good now!

**Comment by Chevalier-Maxime** [comment]
Hello there,
I have the same issue for otf2/otf trace (I can't run any traces). It's not traces I had generated myself (I took traces from different issues).

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Processing /home/chevamax/Documents/Stage-LIG-2017/simulationBefore/Small/wrf.otf
Reading definitions
Reading events
Finish reading
0 unmatched sends and 0 unmatched recvs.
OTF Reading: 0.721569 seconds 
Event/Message Matching: 0.966879 seconds 
Merging for messages...
Partition Merge: 0.19727 seconds 
Message Merge: 0.369709 seconds 
Merging cycles...
Setting partition dag...
Tarjan... 
Merging from the cycles...
Partition Merge: 0.167061 seconds 
Cycle Merge: 0.334831 seconds 
Setting DAG leaps...
Assigning local steps
Local Stepping: 0.0709713 seconds 
Setting global steps
Global Stepping: 0.0265932 seconds 
Total Algorithm Time: 0.836623 seconds 
Calculating step-wise metrics
Metrics Calculation: 0.830763 seconds 
Gnomifying...
Structure Extraction: 1.73393 seconds 
Total Algorithm Time: 0.836623 seconds 
Total trace: 3.57619 seconds 
QThread: Destroyed while thread is still running
Abandon (core dumped)

**Comment by kisaacs** [comment]
@Chevalier-Maxime Thanks for letting me know! I'm traveling but will try look into it in a few days. Can you tell me which versions of the dependencies you are using and your OS?

**Comment by Chevalier-Maxime** [comment]
@kisaacs Hi! Thanks for the fast response !
I use Ubuntu gnome 17.04, with :
- `otf2-config --version` : version 2.0
- `qtpaths --qt-version` : 5.9.0 
- muster : via the git
- `cmake --version` : 3.7.2
- `otfinfo -V` : 1.12.5 "salmon"

Tell me if you need anything else

**Comment by kisaacs** [comment]
Sorry for the slow fix. I just changed the importThread handling. This fixed it on my VM.

Note though that for the Small WRF example, Ravel won't do anything because Ravel operates on sends/receives. However, there is a branch called basic-otf2 that just shows the normal Gantt chart and will open it.
